import DarkModeButton from "@/components/ui/darkModeButton/DarkModeButton";
import "./globals.css";
import ClientProvider from "@/components/clientProvider/ClientProvider";

export const metadata = {
  title: "Shop Sphere",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="dark:bg-dark">
        <ClientProvider>{children}</ClientProvider>
      </body>
    </html>
  );
}
